name: Prepare Release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare_release:
    name: Prepare Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build
        run: |
          GOARCH=amd64 go build -o bin/cron-control-runner-linux-amd64 main.go
          GOARCH=arm64 go build -o bin/cron-control-runner-linux-arm64 main.go
        env:
          CGO_ENABLED: 0
          GOOS: linux

      - name: Attest build provenance
        id: attest
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: |
            bin/cron-control-runner-linux-amd64
            bin/cron-control-runner-linux-arm64

      - name: Generate provenance file
        run: |
          jq .dsseEnvelope "${{ steps.attest.outputs.bundle-path }}" > bin/cron-control-runner.intoto.jsonl

      - name: Create a release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          generate_release_notes: true
          files: |
            bin/cron-control-runner-linux-amd64
            bin/cron-control-runner-linux-arm64
            bin/cron-control-runner.intoto.jsonl
