name: Run tests
on:
  push:
  	branches: [ trunk ]
  pull_request:
  	branches: [ trunk ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
		- uses: actions/checkout@v3
		- uses: actions/setup-go@v3
		- run: go version
		- run: go build
        - run: go test ./...
