name: Run tests
on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Go Dependencies
        # https://github.com/actions/setup-go/issues/130
        # See: https://github.com/actions/cache/blob/95f200e41cfa87b8e07f30196c0df17a67e67786/examples.md#go---modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go version
      - run: go build
      - run: go test ./...
